import type { Metadata } from 'next';
import Link from 'next/link';
import Logo from '@/components/Logo';
import Footer from '@/components/Footer';
import { COLORS, CONTACT_EMAIL, SITE_URL } from '@/lib/constants';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'Blanked privacy policy - what we collect, how we use it, who we share it with, and your rights. We never sell your data.',
  alternates: { canonical: `${SITE_URL}/privacy` },
  openGraph: {
    title: 'Privacy Policy | Blanked',
    description: 'What we collect, how we use it, who we share it with, and your rights. We never sell your data.',
    url: `${SITE_URL}/privacy`,
    images: ['/opengraph-image'],
  },
  twitter: {
    card: 'summary',
    title: 'Privacy Policy | Blanked',
    description: 'What we collect, how we use it, and your rights.',
  },
};

const sectionStyle: React.CSSProperties = { marginBottom: 36 };
const h2Style: React.CSSProperties = { fontSize: 22, fontWeight: 700, color: COLORS.text, marginBottom: 12 };
const h3Style: React.CSSProperties = { fontSize: 16, fontWeight: 700, color: COLORS.text, marginBottom: 8, marginTop: 16 };
const pStyle: React.CSSProperties = { fontSize: 16, color: COLORS.textM, lineHeight: 1.7, marginBottom: 12 };
const ulStyle: React.CSSProperties = { fontSize: 16, color: COLORS.textM, lineHeight: 1.7, marginBottom: 12, paddingLeft: 24 };
const linkStyle: React.CSSProperties = { color: COLORS.accent, textDecoration: 'underline' };

export default function PrivacyPage() {
  return (
    <div style={{ width: "100%", maxWidth: 960, margin: "0 auto", background: COLORS.bg, minHeight: "100vh" }}>
      {/* NAV */}
      <div style={{ padding: "16px 24px", display: "flex", alignItems: "center", gap: 10 }}>
        <Link href="/" aria-label="Blanked home" style={{ display: "flex", alignItems: "center", gap: 10, textDecoration: "none" }}>
          <Logo size={36} id="privacy-nav" />
          <span style={{ fontSize: 18, fontWeight: 800, color: COLORS.text }}>
            <span style={{ color: COLORS.accent }}>Blanked</span>
          </span>
        </Link>
      </div>

      <div style={{ maxWidth: 720, margin: "0 auto", padding: "40px 24px 80px" }}>
        <h1 style={{ fontSize: 38, fontWeight: 800, color: COLORS.text, marginBottom: 8, letterSpacing: -0.5 }}>Privacy Policy</h1>
        <p style={{ fontSize: 14, color: COLORS.textD, marginBottom: 40 }}>Last updated: 14 April 2026</p>

        <div style={sectionStyle}>
          <p style={pStyle}>
            We built Blanked because we love memory games and we respect the people who play them. This policy explains, in plain English, what we collect, why we collect it, who we share it with, and what rights you have. No dark patterns, no selling your data, no surprises.
          </p>
          <p style={pStyle}>
            If anything here is unclear, email us at{' '}
            <a href={`mailto:${CONTACT_EMAIL}`} style={linkStyle}>{CONTACT_EMAIL}</a>
            {' '}and we&apos;ll explain it.
          </p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>Who we are</h2>
          <p style={pStyle}>
            Blanked is operated from Gibraltar. When we say &ldquo;Blanked&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo; in this policy, we mean the operators of the Blanked mobile app and this website. We are the data controller for the personal information described below.
          </p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>What we collect</h2>
          <p style={pStyle}>Here&apos;s everything we collect, and why.</p>

          <h3 style={h3Style}>Account information</h3>
          <ul style={ulStyle}>
            <li><strong>Account ID</strong> - a random UUID generated by our auth system so we can tell one player from another</li>
            <li><strong>Email address</strong> - from Apple Sign In (which may be a real address or Apple&apos;s private relay address, your choice) or from email sign-up. Used solely for account recovery and important account-related emails. We don&apos;t send marketing unless you opt in.</li>
            <li><strong>Username</strong> - the name you pick; visible to your friends and on leaderboards</li>
            <li><strong>Profile photo</strong> - only if you upload one. Stored in Supabase Storage.</li>
          </ul>

          <h3 style={h3Style}>Gameplay data</h3>
          <ul style={ulStyle}>
            <li>Levels played, stars earned, world progression, memory-score averages</li>
            <li>Power-up usage, gems earned and spent, in-app purchase records</li>
            <li>Daily activity timestamps (for streak tracking)</li>
            <li>Streak length, streak-shield count, last-play date (for streak recovery)</li>
            <li>Tutorial-seen flag (so we don&apos;t show tutorials twice)</li>
            <li>Cosmetic loadout (equipped frame, banner, avatar expression)</li>
            <li>Subscription status (for Blanked+ entitlement)</li>
            <li>Notification preferences</li>
          </ul>
          <p style={pStyle}>
            We use this data to save your progress, balance game difficulty, power our admin analytics dashboard (so we know which levels are too hard or too easy), and deliver the subscription features you&apos;ve paid for.
          </p>

          <h3 style={h3Style}>Social data</h3>
          <ul style={ulStyle}>
            <li>Friend connections (who you&apos;ve added / accepted)</li>
            <li>Head-to-head challenge results with your friends</li>
          </ul>

          <h3 style={h3Style}>Device and technical data</h3>
          <ul style={ulStyle}>
            <li><strong>Push notification token</strong> - an anonymous device identifier from Expo, so we can send streak reminders and friend-challenge alerts (only with your permission)</li>
            <li><strong>Advertising identifier (IDFA on iOS)</strong> - <em>only</em> if you grant App Tracking Transparency permission. If you say no (or don&apos;t answer), we serve non-personalised ads instead. You can change this any time in iOS Settings → Privacy → Tracking.</li>
            <li><strong>IP address</strong> - seen by ad networks and our hosting provider as a normal part of internet traffic. Not stored in our app database.</li>
          </ul>

          <h3 style={h3Style}>Purchase data</h3>
          <ul style={ulStyle}>
            <li>Transaction records for in-app purchases (processed by Apple - <em>we never see your card or payment details</em>)</li>
            <li>RevenueCat subscription status (for Blanked+)</li>
          </ul>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>What we don&apos;t collect</h2>
          <ul style={ulStyle}>
            <li>Your real name, unless you choose to put it in your username or display name</li>
            <li>Your location (no GPS, no geolocation APIs)</li>
            <li>Your contacts or address book</li>
            <li>Your camera roll or photos (other than the one profile photo you explicitly upload)</li>
            <li>Your browsing history</li>
            <li>Your microphone or camera in real-time</li>
          </ul>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>What other players can see</h2>
          <p style={pStyle}>When you connect with friends in Blanked, they can see:</p>
          <ul style={ulStyle}>
            <li>Your username</li>
            <li>Your profile photo (if uploaded)</li>
            <li>Your equipped cosmetics - frame, banner, avatar expression</li>
            <li>Your total stars, highest world reached, memory-score average, and current streak length</li>
            <li>Your head-to-head challenge results with them</li>
            <li>Your online / recently active / offline status</li>
          </ul>
          <p style={pStyle}>
            Your email address, account ID, purchase history, streak-shield count, and daily activity timestamps are <strong>never</strong> shown to other players.
          </p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>Third-party services</h2>
          <p style={pStyle}>Blanked uses the following services. Each one gets the minimum data needed to do its job.</p>
          <ul style={ulStyle}>
            <li><strong>Supabase</strong> - our database and authentication provider. Stores your account, gameplay data, profile photo, and friend connections. Servers located in the EU (London, eu-west-2).</li>
            <li><strong>Apple Sign In</strong> - authentication. Apple hands us your account ID and either your real email or a private relay address (your choice).</li>
            <li><strong>RevenueCat</strong> - manages subscription entitlements (Blanked+). Sees your Apple purchase receipts but not your card details.</li>
            <li><strong>Expo</strong> - push notifications. Stores the anonymous push token we use to send your streak reminders and challenge alerts.</li>
            <li><strong>Google AdMob</strong> (via <code>react-native-google-mobile-ads</code>) - serves in-app advertising. AdMob may collect your device advertising identifier, IP address, and ad-interaction data. If you&apos;ve granted App Tracking Transparency permission, ads may be personalised; otherwise, they&apos;re non-personalised. See{' '}
              <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" style={linkStyle}>Google&apos;s privacy policy</a> for details.
            </li>
            <li><strong>Apple App Store</strong> - processes your in-app purchases. Governed by{' '}
              <a href="https://www.apple.com/legal/privacy/" target="_blank" rel="noopener noreferrer" style={linkStyle}>Apple&apos;s privacy policy</a>.
            </li>
          </ul>
          <p style={pStyle}>
            In the future we may add <strong>Sentry</strong> for crash reporting. We&apos;ll update this policy and notify users before that ships.
          </p>
          <p style={pStyle}>
            <strong>We do not sell your data.</strong> Not to advertisers, not to data brokers, not to anyone. Data is only shared with the services above, and only as far as necessary for them to function.
          </p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>Advertising and tracking</h2>
          <p style={pStyle}>
            Blanked shows ads from Google AdMob to support the free-to-play experience. On iOS, Apple requires us to ask for your permission before tracking you across apps (App Tracking Transparency). When you first launch Blanked, you&apos;ll see Apple&apos;s standard prompt.
          </p>
          <ul style={ulStyle}>
            <li>If you <strong>allow tracking</strong>, AdMob may use your device advertising identifier (IDFA) to show ads that are more relevant to you</li>
            <li>If you <strong>don&apos;t allow tracking</strong>, AdMob serves non-personalised ads based only on coarse signals like the app category</li>
            <li>You can change your choice any time in iOS <strong>Settings → Privacy &amp; Security → Tracking</strong>, or switch off personalised ads entirely in <strong>Settings → Privacy &amp; Security → Apple Advertising</strong></li>
          </ul>
          <p style={pStyle}>
            Blanked+ subscribers don&apos;t see ads.
          </p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>International data transfers</h2>
          <p style={pStyle}>
            Our databases are hosted by Supabase in the EU (London, <code>eu-west-2</code>). Some of our other providers - Apple, Google (AdMob), and Expo - may process your data in the United States or other countries. Where personal data is transferred outside the UK / EEA / Gibraltar, we rely on Standard Contractual Clauses (SCCs) approved by the relevant authorities to ensure your data is protected to an equivalent standard.
          </p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>Legal basis for processing</h2>
          <p style={pStyle}>
            If you&apos;re in the UK, EEA, or Gibraltar, we rely on one of the following legal bases for each type of processing:
          </p>
          <ul style={ulStyle}>
            <li><strong>Contract</strong> - to provide the Blanked service you signed up for (account management, gameplay, purchases, subscription entitlement, friend features)</li>
            <li><strong>Legitimate interests</strong> - game-balance analytics, fraud prevention, product improvement. You can object to this processing any time - see &ldquo;Your rights&rdquo; below.</li>
            <li><strong>Consent</strong> - personalised advertising (where you granted App Tracking Transparency permission), push notifications, optional marketing emails. You can withdraw consent at any time.</li>
            <li><strong>Legal obligation</strong> - keeping purchase records for tax and consumer-rights compliance</li>
          </ul>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>Your rights</h2>
          <p style={pStyle}>
            Under Gibraltar, UK, and EU data-protection law, you have the following rights. We&apos;ll respond to any request within 30 days.
          </p>
          <ul style={ulStyle}>
            <li><strong>Right of access</strong> - request a copy of the personal data we hold about you</li>
            <li><strong>Right to rectification</strong> - correct inaccurate or incomplete data</li>
            <li><strong>Right to erasure</strong> (&ldquo;right to be forgotten&rdquo;) - delete your account and all associated data. You can do this yourself at any time from <strong>Settings → Profile → Delete Account</strong> inside the app, or by emailing us.</li>
            <li><strong>Right to data portability</strong> - receive your data in a portable, machine-readable format</li>
            <li><strong>Right to restrict processing</strong> - ask us to pause certain uses of your data</li>
            <li><strong>Right to object</strong> - object to processing based on legitimate interests (e.g. analytics) or direct marketing</li>
            <li><strong>Right to withdraw consent</strong> - for anything you previously consented to (such as personalised ads or push notifications)</li>
            <li><strong>Right to lodge a complaint</strong> - with your local data-protection authority:
              <ul style={{ ...ulStyle, marginTop: 6, paddingLeft: 20 }}>
                <li>Gibraltar: Gibraltar Regulatory Authority -{' '}
                  <a href="https://www.gra.gi" target="_blank" rel="noopener noreferrer" style={linkStyle}>gra.gi</a>
                </li>
                <li>UK: Information Commissioner&apos;s Office -{' '}
                  <a href="https://ico.org.uk" target="_blank" rel="noopener noreferrer" style={linkStyle}>ico.org.uk</a>
                </li>
                <li>EU: your national supervisory authority (see{' '}
                  <a href="https://edpb.europa.eu/about-edpb/about-edpb/members_en" target="_blank" rel="noopener noreferrer" style={linkStyle}>edpb.europa.eu</a>)
                </li>
              </ul>
            </li>
          </ul>
          <p style={pStyle}>
            To exercise any of these rights, email{' '}
            <a href={`mailto:${CONTACT_EMAIL}`} style={linkStyle}>{CONTACT_EMAIL}</a>.
          </p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>Data retention</h2>
          <ul style={ulStyle}>
            <li><strong>Account data</strong> - kept while your account is active. When you delete your account (in-app or by request), we remove it from our live systems within 30 days.</li>
            <li><strong>Backups</strong> - Supabase retains encrypted backups for up to 7 days after deletion for disaster recovery. After that window your data is unrecoverable.</li>
            <li><strong>Analytics events</strong> (game-balance and economy data) - kept for up to 24 months, after which they&apos;re either anonymised or deleted</li>
            <li><strong>Purchase records</strong> - kept for as long as required by tax and consumer-protection law (typically 6 years in the UK / Gibraltar)</li>
          </ul>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>Data security</h2>
          <p style={pStyle}>
            We implement appropriate technical and organisational measures to protect your personal data - encrypted connections (HTTPS/TLS everywhere), row-level security on our database, hashed authentication tokens, and principle-of-least-privilege access for our team. No internet transmission or storage system is ever 100% secure, but we take this seriously and treat any breach as the emergency it is.
          </p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>Children&apos;s privacy</h2>
          <p style={pStyle}>
            Blanked is rated 4+ on the App Store - it&apos;s a memory game with no violent or adult content. That said, we don&apos;t knowingly collect personal information from children under 13 (or the relevant age in your country - this can be as high as 16 in some EU member states) without verifiable parental consent.
          </p>
          <p style={pStyle}>
            If you&apos;re a parent or guardian and you believe your child signed up without your permission, email us at{' '}
            <a href={`mailto:${CONTACT_EMAIL}`} style={linkStyle}>{CONTACT_EMAIL}</a>
            {' '}and we&apos;ll delete the account promptly.
          </p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>Changes to this policy</h2>
          <p style={pStyle}>
            We may update this Privacy Policy from time to time. When we make material changes - like adding a new third-party service or changing how we use your data - we&apos;ll notify you in-app before they take effect. The &ldquo;Last updated&rdquo; date at the top of this page always reflects the current version.
          </p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>Contact us</h2>
          <p style={pStyle}>
            Questions about this policy? Want to exercise your data rights? Just reply to any of our emails, or contact us directly:
          </p>
          <p style={pStyle}>
            <strong>Email</strong>:{' '}
            <a href={`mailto:${CONTACT_EMAIL}`} style={linkStyle}>{CONTACT_EMAIL}</a>
          </p>
          <p style={pStyle}>
            Users in the UK, EEA, or Gibraltar can reach our data-protection contact at the same address.
          </p>
        </div>
      </div>

      <Footer />
    </div>
  );
}
